name       : python-backports.ssl_match_hostname
version    : 3.5.0.1
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/b/backports.ssl_match_hostname/backports.ssl_match_hostname-3.5.0.1.tar.gz : 502ad98707319f4a51fa2ca1c677bd659008d27ded9f6380c79e8932e38dcdf2
license    : Python-2.0
component  : programming.python
summary    : The ssl.match_hostname() function from Python 3.5
description: |
    The ssl.match_hostname() function from Python 3.5
rundeps    :
    - python-backports
    - python-ipaddress
build      : |
    %python_setup
install    : |
    %python_install
    rm $installdir/usr/lib/python2.7/site-packages/backports/__init__.py*
