name       : python-backports.ssl_match_hostname
version    : 3.7.0.1
release    : 4
source     :
    - https://files.pythonhosted.org/packages/ff/2b/8265224812912bc5b7a607c44bf7b027554e1b9775e9ee0de8032e3de4b2/backports.ssl_match_hostname-3.7.0.1.tar.gz : bb82e60f9fbf4c080eabd957c39f0641f0fc247d9a16e31e26d594d8f42b9fd2
license    : Python-2.0
component  : programming.python
summary    : The ssl.match_hostname() function from Python 3.5
description: |
    The ssl.match_hostname() function from Python 3.5
rundeps    :
    - python-backports
    - python-ipaddress
build      : |
    %python_setup
install    : |
    %python_install
    rm $installdir/usr/lib/python2.7/site-packages/backports/__init__.py*
